spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables automatic service discovery in Eureka
          lower-case-service-id: true  # Ensures service IDs are in lowercase
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**  # Public routes for Login & Registration
          filters:
            - PreserveHostHeader  # Ensures correct host forwarding

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - RemoveRequestHeader=Cookie  # Ensures clean requests
            - RewritePath=/api/tasks/(?<path>.*), /$\{path}  # Rewrites path

        - id: reward-service
          uri: lb://reward-service
          predicates:
            - Path=/api/rewards/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/rewards/(?<path>.*), /$\{path}

        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/store/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/store/(?<path>.*), /$\{path}

      default-filters:
        - PreserveHostHeader  # Ensures proper forwarding of headers
        - RemoveRequestHeader=Cookie  # Avoids unnecessary cookies being passed

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
  instance:
    prefer-ip-address: true  # Uses IP address instead of hostname
